language: python

# let's test as many versions as we can!
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "nightly"

# we don't need any python dependencies:
install: true

# the test command:
script: python ./setup.py test

# no need for sudo access, silence notice:
sudo: false

# enable OSX support, with only system python:
matrix:
    include:
        - os: osx
          language: generic
          python:
